//USER ROLES ENUMS
const USER_ROLES = {
  ADMIN: "ADMIN",
  PROJECT_ADMIN: "PROJECT_ADMIN",
  MEMBER: "MEMBER",
};

const USER_ROLES_ENUM = Object.values(USER_ROLES);

export { USER_ROLES, USER_ROLES_ENUM };

//TASK STATUS ENUMS
const TASK_STATUS = {
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  DONE: "DONE",
};

const TASK_STATUS_ENUM = Object.values(TASK_STATUS);

export { TASK_STATUS, TASK_STATUS_ENUM };
