const STATUS_CODE = {
  CONTINUE: 100, //SERVER HAS RECEIVED HEADERS AND CAN SEND BODY
  SWITCHING_PROTOCOL: 101, //LETS SAY HTTP TO WEB SOCKETS

  OK: 200,
  RESOURSE_CREATED: 201,
  DELETED_SUCCESSFULLY: 204,

  REDIRECT: 301, // URL HAS PERMANENTLY MOVED
  FOUND: 302, //URL HAS MOVED BUT THIS IS ONE IS STILL RUNNING
  NOT_MODIFIED: 304,

  BAD_REQUEST: 400, // DATA VALIDATION FAILED
  UNAUTHORIZED: 401, // NOT AUTHORIZED WITH TOKENS OR NOT LOGGED IN
  FORBIDDEN: 403, // ACCESSING ADMIN DATA WITHOUT BEING ADMIN
  NOT_FOUND: 404, //DATA NOT FOUND OR USER NOT FOUND
  TOO_MANY_REQUEST: 429, // HITTING RATE LIMIT

  INTERNAL_SERVER_ERROR: 500, //INTERNAL SERVER ERROR
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503, //MAINTAINANCE
};

export { STATUS_CODE };
